### PR TITLE
fix(canon): route workspace package Vue exports in editor

### LINKED ISSUE #4000: fix(canon): resolve workspace package Vue exports through virtual mirror
## Severity
P0 false negative / false positive pair.

## Reproduction
A workspace package is linked through `node_modules`, and its `package.json#exports` subpath targets `src/Widget.vue`. An app imports that bare package subpath.

- Default `vize check` discovers and diagnoses the external SFC, but the importing TS file also reports TS2882 because the bare package specifier still resolves to the real `.vue` target rather than the external virtual mirror.
- Explicit `vize check src/entry.ts` drops the external SFC virtual registration at the explicit-root boundary, leaving only TS2882 and no SFC diagnostic.

## Required behavior
- Preserve package export/self-reference identity while routing `.vue` targets to generated external-mirror modules.
- Work for default and explicit subsets, scoped packages, root/subpath/wildcard exports, symlinked pnpm/npm/yarn workspace layouts, and transitive package imports.
- No TS2882/TS2307 false positive.
- Report script and template diagnostics from the package SFC with correct source mapping.
- Keep plain TS/JS package sources in place and do not regress generated GraphQL module identity.
- Cover declaration emit and persistent project-session diagnostics.

Tracks #3984 and the production-readiness roadmap #3957.

### PR DESCRIPTION
**Pull request by ubugeeei**
## Summary

- consolidate CLI, editor, definition, and reverse-import package export routing on one importer-scoped Canon resolver
- materialize workspace package Vue exports and TypeScript barrels for Corsa while preserving authored and declaration package identities
- invalidate editor routes on source, manifest, symlink, and negative package lookup lifecycle changes
- map Corsa external-mirror locations back to authored Vue sources and refresh open importers on manifest/source changes

## Root cause

Editor typechecking did not share the workspace-package export routing already used by the batch path. Bare package imports therefore reached Corsa without a materialized Vue target, and the editor cache did not retain the logical link, physical manifest, or missing lookup candidates needed to observe retargets and later package creation.

The shared route keeps logical package-link identity separate from canonical physical package identity. Cache stamps include content digests and symlink targets, so same-mtime edits, delete/recreate cycles, manifest retargets, invalid JSON repairs, and link retargets all rebuild deterministically.

## Validation

- `cargo check -p vize_canon -p vize_maestro -p vize`
- no-default-feature checks for Canon and Maestro
- strict lib clippy for all three crates
- Canon: 894 non-Corsa tests plus the isolated Corsa-required test
- Maestro with real Corsa: 742 passed, 2 ignored
- vize: 419 unit tests
- CLI regressions for workspace packages, declarations, GraphQL, allowJs, Vue re-exports, and external imports
- source-length, formatting, and diff checks
- real Corsa regressions prove direct exports, TypeScript barrels, and absent-to-created packages resolve without degrading the component to `any`

Closes #4000

---
<a href="https://app.blacksmith.sh/ubugeeei-prod/codesmith/vize/pr/4100"><picture><source media="(prefers-color-scheme: dark)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/view-with-codesmith-dark-v2.svg"><source media="(prefers-color-scheme: light)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/view-with-codesmith-light-v2.svg">View with [code]smith</picture></a>
<sup>Need help on this PR? Tag <code>@codesmith-bot</code> with what you need. Autofix is enabled.</sup>

## Summary by CodeRabbit

* **New Features**
  * Improved resolution of package exports, workspace packages, aliases, Vue files, and TypeScript/JavaScript sources.
  * Added support for JSX sources, symlinked packages, and external mirror paths when navigating to definitions.
  * Added source tracking and recovery when package manifests, files, or links change.

* **Bug Fixes**
  * Fixed unresolved imports and diagnostics after package creation, renaming, or manifest updates.
  * Improved dependency scanning and type-checking updates for package and declaration files.

* **Tests**
  * Expanded coverage for package routing, export conditions, workspace sources, caching, and invalidation.

### CODE REVIEW

**Comment by ubugeeei** [comment]
CI ablation for latest head `4dbf2e56e`:

- The required `clippy-and-test` failure is an existing real-Corsa parallel-session race, not the #4000 package-route path: the failing event-rename test has no implementation delta from green head `14b6c67f`.
- CI failed with `didOpen: context canceled` / `RequestCancelled`; the exact failing test passes in isolation with pinned Corsa v0.52.
- Enabling the real binary for the full parallel Maestro suite moves the failure to a sibling event-rename test (`save` range vs exact `save-item`); that sibling also passes in isolation.
- Tracked separately as #4118 with a deterministic concurrent regression and no-retry/no-serialization acceptance criteria.

Auto-merge remains disabled. I will rerun the failed required job once after the current workflow completes; any recurrence stops this PR rather than retrying again.
