### ISSUE TITLE
canon: exactOptionalPropertyTypes is not honored for component props (vue-tsc reports TS2379)

### ISSUE THREAD

**Issue by ubugeeei** [ubugeeei/vize#3450]
Found while building vue-tsc oracles for the #3222 parity scorecard.

With `exactOptionalPropertyTypes: true`, passing an explicitly `undefined` value
to an optional child prop is an error for vue-tsc and silent for vize.

## Reproduction

`src/Child.vue`

```vue
<script setup lang="ts">
defineProps<{ label?: string }>()
</script>

<template><span /></template>
```

`src/Parent.vue`

```vue
<script setup lang="ts">
import Child from './Child.vue'
const maybe: string | undefined = undefined
</script>

<template><Child :label="maybe" /></template>
```

`tsconfig.json`: `strict: true`, `exactOptionalPropertyTypes: true`,
`moduleResolution: "bundler"`, `noEmit: true`,
`lib: ["ES2022", "DOM", "DOM.Iterable"]`, `types: []`.

## Oracle

vue-tsc 3.3.4:

```
src/Parent.vue(6,12): error TS2379: Argument of type '{ label: undefined; }' is not assignable to parameter of type '{ readonly label?: string; } & VNodeProps & AllowedComponentProps & ComponentCustomProps & Record<string, unknown>' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
```

`vize check --format json` (build of `main` at 20408f80f):

```
(no diagnostics)
```

Classification: **vize false negative**, and specifically a `tsconfig`-honoring
one: the option is set, tsc obeys it, vize's generated code cannot express it.

## Why

`exactOptionalPropertyTypes` distinguishes *"the property is absent"* from
*"the property is present and `undefined`"*. That distinction only exists when a
whole object literal is assigned to the target type. vize checks props one at a
time —
`const __vize_prop_check_0_label: __Child_0_prop_label = maybe;` — where the
extracted per-prop type is `string | undefined`, so the assignment is legal no
matter what the option says.

This is the same structural cause as #3444 (`v-bind="object"` unchecked): both
need a whole-props-object check for the component usage, which is also the shape
vue-tsc's `TS2345`/`TS2379` diagnostics take (anchored at the element name,
column 12 here). Worth fixing the two together.

The generic-inference call in
`crates/vize_canon/src/virtual_ts/expressions/component_props.rs` already
assembles an object literal for the usage, but it resolves to a
`(props: any) => void` no-op for a non-generic child (see `__VizePropChecker` in
`virtual_ts/scope.rs`), so nothing is checked. Making that checker resolve to
the child's real props type for non-generic components looks like the smallest
change that covers both issues.

**Comment by ubugeeei** [comment]
Investigated but not landed in this pass. Recording what is already established so
the next attempt does not re-derive it, and so the false-positive risk is on the
record before someone turns this on.

## The pieces that already exist

The child's real props type is **already resolved** in the generated virtual TS.
`crates/vize_canon/src/virtual_ts/scope/component_props.rs` emits, per usage:

```ts
type __Child_Props_0 = typeof Child extends { __vizeCheck: any }
  ? Record<string, unknown>
  : (typeof Child extends { new (): { $props: infer __P } } ? __P
    : (typeof Child extends (props: infer __P) => any ? __P : {}));
```

and the per-prop aliases are `__VizePropValue<__Child_Props_0, 'label'>` — the
extraction that flattens `label?: string` to `string | undefined` and thereby
loses the `exactOptionalPropertyTypes` distinction this issue is about.

The whole-object call site exists too:

```ts
(undefined as unknown as __Child_Check_0)({ "label": maybe, });
```

`__Child_Check_0` is `__VizePropChecker<typeof Child, __Child_CheckProps_0>`, and
for a non-generic child every branch of `__VizePropChecker` collapses to
`(props: P & Record<string, unknown>) => void` where `P`
(`__Child_CheckProps_0`, built by `scope/component_prop_checker.rs::append_prop_checker_alias`)
contains only *inline function* props. So the call checks essentially nothing.

So the wiring is one type-alias edit away: point the non-generic branch at
`__Child_Props_0` instead of the near-empty `P`.

## Why that edit is not a small change

Making the object literal check against the child's full props type also turns on
**missing required prop** reporting, because the literal only carries the props the
template authored. That is what vue-tsc does, and it is a whole new diagnostic
class for vize, gated on vize's props extraction being right for every component
shape it meets — `defineComponent` with runtime props, mixins, library components,
`DefineComponent` re-exports, Options API. Any gap becomes a false positive on
correct user code.

`v-bind="obj"` makes it worse, and is the reason #3444 and #3450 cannot be split:
a `<Child v-bind="bag" />` usage contributes **no** entries to `usage.props`
(`crates/vize_canon/src/virtual_ts/expressions/component_props.rs` iterates
`usage.props`, which are named bindings only), so the object literal for that
usage is empty and every required prop of the child would be reported missing.
Turning on the whole-object check without first folding the spread into the same
literal would produce a false positive on every spread usage in the ecosystem.

## Suggested shape

1. Fold `v-bind="obj"` into the same literal the generic-inference call already
   assembles, as a spread: `({ ...bag, "label": maybe })`. Anchor its mapping at
   the `v-bind` directive name — the oracle in #3444 reports at column 12, the
   directive, not the expression.
2. Point the non-generic `__VizePropChecker` branch at the child's resolved props
   type. If the missing-required-prop class turns out to be too noisy to enable in
   one step, `Pick<__Child_Props_0, <authored keys>>` is the intermediate: it keeps
   each authored prop's declared optionality — which is all
   `exactOptionalPropertyTypes` needs to produce the `TS2379` in #3450 — while
   reporting nothing about props the template did not pass. #3444 still needs the
   full type, because the spread's key set is not statically known.
3. Validate against the hydrated ecosystem slices with
   `tools/fixtures/typecheck-divergence.mjs` before landing, and keep
   `tests/tooling/compat-ratchet.test.ts` at 0 FP / 0 FN. #3443 is the cautionary
   tale here: three separate downstream failures surfaced one after another, each
   only visible from a different consumer of the generated program.

## Oracle positions to match

- #3444: `src/Parent.vue(6,12): error TS2345` — column 12 is the `v-bind`
  directive name.
- #3450: `src/Parent.vue(6,12): error TS2379` — same anchor. TypeScript reports an
  argument-assignability error at the argument expression, so the whole object
  literal's generated range must map to the element/directive span, not to any
  single property.

**Comment by ubugeeei** [comment]
Attempted and **not landed**. Four things are now settled empirically; recording them so the next attempt starts from here.

## 1. `Partial<__X_Props_N>` is the right target, and it decouples this issue from #3444

Pointing `__X_CheckProps_N` at `Partial<__X_Props_N>` — rather than the near-empty inline-function object it carries today — gives exactly the wanted check and nothing more. `__VizePropChecker` already intersects it with `Record<string, unknown>`. Verified against `tsgo 7.0.0-dev` on a hand-written fixture, one case per row:

| literal | want | got |
| --- | --- | --- |
| `{ "label": maybe }` where `label?: string` | error (this issue) | ✅ error |
| `{ "count": "oops" }` where `count: number` | error | ✅ error |
| `{ "label": "ok" }`, `count` omitted | **clean** — no missing-required-prop | ✅ clean |
| `{ "label": "ok", "data-id": 1 }` | **clean** — fallthrough attr | ✅ clean |
| `{ "count": undefined }` where `count: number` | error | ✅ error |
| `{}` | clean | ✅ clean |
| `{ "pick": (i) => String(i) }` | clean — callback contextually typed | ✅ clean |
| `{ "pick": (i) => i }` returning the wrong type | error | ✅ error |

`Partial` is what makes the missing-required-prop class stay off, which is the whole reason the earlier analysis said this issue and #3444 could not be split. With `Partial` they can: a usage carrying only `v-bind="obj"` contributes no entries to `usage.props`, so `has_inference_props` is already false and no call is emitted at all — this issue's fix simply never runs on it.

`Partial` also removes the one real fragility in the design. A `Pick<__X_Props_N, <authored keys>>` would have had to reproduce the literal's own skip logic exactly — the literal drops props whose value does not generate — or report phantom missing properties. Every property being optional makes the alias and the literal independent.

## 2. It double-reports, and that is the blocker

Enabling the whole-object check **alongside** the existing per-prop check reports every wrongly-typed prop twice, at two anchors, with an identical message and code. `dedup_diagnostics` does not collapse them because the positions differ:

```
6:10:error Type 'string' is not assignable to type 'number'.   <- new, object literal entry
6:11:error Type 'string' is not assignable to type 'number'.   <- existing, per-prop check
```

`argument_less_v_model_anchors_at_the_directive` shows the same shape one directive apart (`10:25` beside `10:33`). 10 tests in `vize_canon` fail this way; they are not snapshot churn.

So the remaining work is not "turn the checker on" — it is **deciding which of the two paths owns each diagnostic**. Either the per-prop check stops reporting assignability for props the object check covers, or the object literal's entry spans are mapped onto the per-prop anchors so the pair dedupes. The second keeps every existing anchor and is the smaller change, but it conflicts with #3444's oracle, which wants the whole-object error at the element.

## 3. The code will be `TS2345`, not `TS2379`

This issue's oracle expects `TS2379`. vize cannot produce it. Running **both** compilers over the same file with the same target type:

```
tsc 6.0.3                    -> error TS2379
tsgo 7.0.0-dev (native)      -> error TS2345   (same text, nested one level down)
```

Five target shapes were tried — bare object type, intersected with `Record<string, unknown>`, through `Pick<>`, and vue-tsc's exact `{ readonly label?: string } & VNodeProps & AllowedComponentProps & ComponentCustomProps & Record<string, unknown>` — and all five give `TS2379` under 6 and `TS2345` under 7. It is a compiler-version difference, not something the generated code can steer, and it is the same shape as the `TS5101`/`TS5102` pair in #3448. It wants a `compat-documented-differences.json` entry, and the ledger will otherwise score it as one FP plus one FN.

## 4. The concrete reason #3444 cannot use the child's props type unmodified

`v-bind="$attrs"` — the most common spread in the ecosystem — is a false positive against the full type:

```ts
declare const attrs: Record<string, unknown>;
check({ ...attrs });
// error TS2345: Argument of type '{ [x: string]: unknown; }' is not assignable to parameter of type 'ChildProps & Record<string, unknown>'.
```

A statically typed bag that satisfies the child is clean, and one with a wrongly typed prop reports correctly, so the failure is specific to bags whose key set is not statically known. Whatever #3444 does about the spread has to answer this case first.

**Comment by ubugeeei** [comment]
Landed in #3525 with the design decision resolved: the whole-object check widens every property to `{} | null`, so it reports **only** the `exactOptionalPropertyTypes` violation and leaves ordinary type mismatches to the per-prop check at its own anchor. That is what removes the double-report described above.

Two further findings from the implementation:

- The check needed a **mapping**, not just a type. TypeScript anchors an argument-assignability failure at the argument expression — the whole object literal — so the diagnostic landed on generated bytes with no authored range and was dropped silently. It fired in the generated program and reported nothing. The literal now maps to the tag name (`usage.start + 1`), which is where vue-tsc anchors it.
- `null` has to be in the widened type. A prop declared `LinkBehavior | null` is legitimately passed `null` and `{}` alone rejects it — caught by an existing test, not by the probes.
