### ISSUE TITLE
patina: nuxt/nuxt-config-keys-order always reports "modules before plugins" regardless of the offending key pair

### ISSUE THREAD

**Issue by ubugeeei** [ubugeeei/vize#3768]
## Summary

`vize/nuxt/nuxt-config-keys-order` correctly detects that a `defineNuxtConfig` object deviates from the canonical key order, but the diagnostic message is hard-coded to the `modules` / `plugins` pair. Whichever key is actually misplaced, the message always reads `Expected config key "modules" to come before "plugins"`, and the span points at the whole config object.

The result is a rule that reports a real problem but gives no way to find or fix it. Moving `modules` above `plugins` — the one thing the message asks for — changes nothing.

## Version

- `vize@0.318.0` / `oxlint-plugin-vize@0.318.0`
- `vite-plus@0.2.7`

## Reproduction

`vite.config.mts`:

```ts
import { createVizeLintConfig } from 'oxlint-plugin-vize'
import { defineConfig } from 'vite-plus'

export default defineConfig({
  lint: createVizeLintConfig({ preset: 'nuxt' })
})
```

| `nuxt.config.ts` keys, in order | result |
| --- | --- |
| `modules`, `plugins` | clean |
| `modules`, `plugins`, `css` | clean |
| `modules`, `css`, `plugins` | `Expected config key "modules" to come before "plugins"` |
| `css`, `modules`, `plugins` | `Expected config key "modules" to come before "plugins"` |
| `ssr`, `modules`, `plugins` | `Expected config key "modules" to come before "plugins"` |
| `modules`, `router`, `plugins` | `Expected config key "modules" to come before "plugins"` |
| `modules`, `components`, `plugins` | `Expected config key "modules" to come before "plugins"` |

```ts
// still reports "modules before plugins"
export default defineNuxtConfig({ ssr: false, modules: [], plugins: [] })
```

```
nuxt.config.ts:1:33: error vize(nuxt/nuxt-config-keys-order): Expected config key "modules" to come before "plugins"
```

The detection itself looks right — every reported case does deviate from the canonical order — so this is a reporting problem, not a false positive.

## Expected

- Name the keys that are actually out of order, e.g. `Expected config key "css" to come after "plugins"`.
- Point the span at the offending property, not at the `defineNuxtConfig(` call.
- Ideally report one diagnostic per misplaced key so `--fix` (or a human) can act on them individually.

## Impact

We had to downgrade this rule to `warn` in a Nuxt 2 (bridge) codebase because there is no actionable path from the message to a fix.

## Possibly related

The canonical order appears to be the Nuxt 3 one (`modules` before `plugins`), while the Nuxt 2 documented template orders `plugins` before `modules`. If `compiler.compatibility.nuxtVersion` is set to `2`, it would be reasonable for the rule to use the Nuxt 2 order, or to stay quiet.
