### ISSUE TITLE
fix: Nested `<ol>`/`<li>` causes "Invalid end tag" compilation error in native template compile

### ISSUE THREAD

**Issue by yamanoku** [ubugeeei/vize#1089]
### Area

CLI

### Version

0.178.0

### Minimal reproduction

```vue
<script setup lang="ts">
  const groups = [{ year: "2024", items: ["a", "b"] }];
</script>

<template>
  <ol>
    <li v-for="g in groups" :key="g.year">
      <span>{{ g.year }}</span>
      <ol>
        <li v-for="item in g.items" :key="item">{{ item }}</li>
      </ol>
    </li>
  </ol>
</template>
```

### Actual behavior

Since vize 0.178.0, the native Rust template compiler fails to compile Vue templates containing nested `<ol>`/`<li>` (or `<ul>`/`<li>`) structures. This worked correctly in vize 0.114.0.

### Error Output

```
[vize] Compilation failed in .../TestNestedOl.vue:
- Template compilation errors: [
      CompilerError { code: InvalidEndTag, message: "Invalid end tag.", loc: ..., source: "</li>" },
      CompilerError { code: InvalidEndTag, message: "Invalid end tag.", loc: ..., source: "</ol>" }
]
```

### Expected behavior

Nested lists are valid HTML. The HTML spec explicitly allows flow content (including `<ol>`/`<ul>`) inside `<li>` elements. The HTML parsing algorithm uses "list item scope" which treats `<ol>`/`<ul>` as barrier elements, so an inner `<li>` should NOT auto-close an outer `<li>`.

The native Rust HTML parser appears to auto-close the outer `<li>` when it encounters an inner `<li>` start tag, without checking whether an `<ol>`/`<ul>` boundary exists between them (i.e., "list item scope" is not respected). This causes the remaining closing tags (`</li>`, `</ol>`) to become orphaned, resulting in InvalidEndTag errors.

### Environment

- OS: WSL2
- Node.js: 24.4.0
- Framework:
    - vize: 0.178.0 (fails) / 0.114.0 (works)
    - @vizejs/vite-plugin: 0.178.0
    - vite: 8.0.16

### Before submitting

- [x] I checked existing issues and pull requests.
- [x] This is not a private security report.

**Comment by ubugeeei** [comment]
Thank you! Please try latest version!
